#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
HOST=${1}
COLLECTION=${2}
MYPOSTMANFILE=$DIR"/lib/mypostman.py"
mitmdump --set host_filter=$HOST --set collection_name=$COLLECTION --ssl-insecure -s "$MYPOSTMANFILE"
